"""Login / logout flows."""

import asyncio
import getpass
import io
import sys
from datetime import date, datetime, timezone

from telethon import errors
from telethon.sessions import StringSession

from . import config
from .client import build_client
from .output import TgError

_MAX_QR_REFRESHES = 5


def render_qr(url: str) -> None:
    """Render a tg://login URL as an ASCII QR in the terminal."""
    import qrcode  # lazy: only needed for login

    qr = qrcode.QRCode(border=1)
    qr.add_data(url)
    qr.make(fit=True)
    buf = io.StringIO()
    qr.print_ascii(out=buf, invert=True)
    print("\nScan with your phone: Telegram Settings → Devices → Link Desktop Device\n")
    print(buf.getvalue())
    print(f"Or open this link on the logged-in phone: {url}\n")


def _seconds_until(qr) -> float:
    try:
        remaining = (qr.expires - datetime.now(timezone.utc)).total_seconds()
        return max(1.0, min(remaining, 120.0))
    except Exception:
        return 120.0


async def _qr_login(args) -> None:
    api_id, api_hash = config.require_credentials()
    client = build_client(StringSession(), api_id, api_hash)
    await client.connect()
    try:
        qr = await client.qr_login()
        render_qr(qr.url)
        for _ in range(_MAX_QR_REFRESHES):
            try:
                await qr.wait(timeout=_seconds_until(qr))
                break
            except asyncio.TimeoutError:
                await qr.recreate()
                print("QR code expired; a new one was generated.", file=sys.stderr)
                render_qr(qr.url)
            except errors.SessionPasswordNeededError:
                pw = getpass.getpass("Two-step verification password: ")
                try:
                    await client.sign_in(password=pw)
                except errors.PasswordHashInvalidError:
                    raise TgError("Incorrect 2FA password.", code=1) from None
                break
        else:
            raise TgError("QR login timed out after several refreshes. Try again.", code=1)
        session_str = StringSession.save(client.session)
    finally:
        await client.disconnect()
    config.write_env(
        "TELEGRAM_SESSION_STRING",
        session_str,
        comment=f"generated by tg login on {date.today()}; keep secret, "
        "do NOT share with the MCP daemon session",
    )
    print("Login successful. Session written to .env — verify with: tg me")


async def _phone_login(args) -> None:
    api_id, api_hash = config.require_credentials()
    client = build_client(StringSession(), api_id, api_hash)
    await client.connect()
    try:
        phone = args.phone or input("Phone number (international format, e.g. +86138...): ")
        await client.send_code_request(phone)
        code = input("Login code: ")
        try:
            await client.sign_in(phone, code)
        except errors.SessionPasswordNeededError:
            pw = getpass.getpass("Two-step verification password: ")
            await client.sign_in(password=pw)
        session_str = StringSession.save(client.session)
    finally:
        await client.disconnect()
    config.write_env(
        "TELEGRAM_SESSION_STRING",
        session_str,
        comment=f"generated by tg login on {date.today()}; keep secret, "
        "do NOT share with the MCP daemon session",
    )
    print("Login successful. Session written to .env — verify with: tg me")


async def cmd_login(args) -> None:
    if args.phone is not None:
        await _phone_login(args)
    else:
        await _qr_login(args)


async def cmd_logout(args) -> None:
    api_id, api_hash = config.require_credentials()
    session_str = config.load_session(getattr(args, "account", None))
    client = build_client(StringSession(session_str), api_id, api_hash)
    await client.connect()
    try:
        await client.log_out()
    finally:
        await client.disconnect()
    config.clear_env(config.session_env_var(getattr(args, "account", None)))
    print("Logged out; session removed from .env. The MCP daemon's session is untouched.")
